// vue/calculator/src/main/Calculator.vue
<template>
  <div class="calculator">
      <Display :value="displayValue"/>
      <Button label="AC" triple @onclick="clearMemory"/>
      <Button label="/" operation @onclick="setOperation"/>
      <Button label="7" @onclick="addDigit"/>
      <Button label="8" @onclick="addDigit"/>
      <Button label="9" @onclick="addDigit"/>
      <Button label="*" operation @onclick="setOperation"/>
      <Button label="4" @onclick="addDigit"/>
      <Button label="5" @onclick="addDigit"/>
      <Button label="6" @onclick="addDigit"/>
      <Button label="-" operation @onclick="setOperation"/>
      <Button label="1" @onclick="addDigit"/>
      <Button label="2" @onclick="addDigit"/>
      <Button label="3" @onclick="addDigit"/>
      <Button label="+" operation @onclick="setOperation"/>
      <Button label="0" double @onclick="addDigit"/>
      <Button label="." @onclick="addDigit"/>
      <Button label="=" operation @onclick="setOperation"/>
  </div>
</template>

<script>
import Display from '../components/Display';
import Button from '../components/Button';

export default {
    data: function () {
        return {
            displayValue: "0",
            cleatDisplay: false,
            operation: null,
            values: [0, 0],
            current: 0
        }
    },
    components: { Button, Display },
    methods: {
        clearMemory() {
            Object.assign(this.$data, this.$options.data());
        },
        setOperation(o) {
            if(this.current === 0) {
                this.operation = o;
                this.current = 1;
                this.cleatDisplay = true;
            } else {
                const equals = o === '=';
                const currentOperation = this.operation;

                try {
                    this.values[0] = eval(
                        `${this.values[0]} ${currentOperation} ${this.values[1]}`
                    )
                } catch (e) {
                    this.$emit('onerror', e);
                }

                this.values[1] = 0
                this.displayValue = this.values[0];
                this.operation = equals ? null : o;
                this.current = equals ? 0 : 1;
                this.cleatDisplay = !equals;
            }
        },
        addDigit(n) {
            if(n == '.' && this.displayValue.includes('.')) {
                return 
            }

            const cleatDisplay = this.displayValue === "0" || this.cleatDisplay;
            const currentValue = cleatDisplay ? "" : this.displayValue;
            const displayValue = currentValue + n;

            this.displayValue = displayValue;
            this.cleatDisplay = false;
            this.values[this.current] = displayValue;
        }
    }
}
</script>

<style>
.calculator {
    height: 320px;
    width: 235px;
    border-radius: 5px;
    overflow: hidden;

    display: grid;
    grid-template-columns: repeat(4, 25%);
    grid-template-rows: 1fr 48px 48px 48px 48px 48px;
}
</style>

// React/calculadora/src/main/Calculator.jsx
import React, { Component } from 'react';
import './Calculator.css';

import Button from '../Components/Button';
import Display from '../Components/Display';

const initialState = {
    displayValue: '0',
    clearDisplay: false,
    operation: null,
    values: [0, 0],
    current: 0
}

export default class Calculator extends Component {

    state = { ...initialState };

    constructor(props) {
        super(props);

        this.clearMemory = this.clearMemory.bind(this);
        this.setOperation = this.setOperation.bind(this);
        this.addDigit = this.addDigit.bind(this);
    }

    clearMemory() {
        this.setState({ ...initialState });
    }

    setOperation(operation) {
        if(this.state.current === 0) {
            this.setState({ operation, current: 1, clearDisplay: true });
        } else {
            const equals = operation === '=';
            const currentOperation = this.state.operation;

            const values = [...this.state.values];
            try {
                values[0] = eval(`${values[0]} ${currentOperation} ${values[1]}`);
            } catch(e) {
                values[0] = this.state.values[0];
            }
            values[1] = 0;

            this.setState({
                displayValue: values[0],
                operation: equals ? null : operation,
                current: equals ? 0 : 1,
                clearDisplay: !equals,
                values
            });
        }
    }

    addDigit(n) {
        if (n === '.' && this.state.displayValue.includes('.')) {
            return 
        }

        const clearDisplay = this.state.displayValue === '0'
            || this.state.clearDisplay;
        const currentValue = clearDisplay ? '' : this.state.displayValue;
        const displayValue = currentValue + n;

        this.setState({ displayValue, clearDisplay: false });

        if(n !== '.') {
            const i = this.state.current;
            const newValue = parseFloat(displayValue);
            const values = [...this.state.values];

            values[i] = newValue;
            this.setState({ values })
        }
    }

    render() {
        return (
            <div className="calculator">
                <Display value={this.state.displayValue}/>
                <Button label="AC" click={this.clearMemory} triple />
                <Button label="/"  click={this.setOperation} operation />
                <Button label="7"  click={this.addDigit}    />
                <Button label="8"  click={this.addDigit}    />
                <Button label="9"  click={this.addDigit}    />
                <Button label="*"  click={this.setOperation} operation />
                <Button label="4"  click={this.addDigit}    />
                <Button label="5"  click={this.addDigit}    />
                <Button label="6"  click={this.addDigit}    />
                <Button label="-"  click={this.setOperation} operation />
                <Button label="1"  click={this.addDigit}    />
                <Button label="2"  click={this.addDigit}    />
                <Button label="3"  click={this.addDigit}    />
                <Button label="+"  click={this.setOperation} operation />
                <Button label="0"  click={this.addDigit} double   />
                <Button label="."  click={this.addDigit}    />
                <Button label="="  click={this.setOperation} operation />
            </div>
        );
    }
}
